export { postLogin } from "./auth/postLogin.js";
export { postRegister } from "./auth/postRegister.js";
export { postPost } from "./post/postPost.js";
export { getAllPost } from "./post/getAllPost.js";
export { deletePost } from "./post/deletePost.js";
export { updatePost } from "./post/updatePost.js";
export { postComment } from "./comment/postComment.js";
export { getUserPost } from "./post/getUserPost.js";
export { getOnePost } from "./post/getOnePost.js";
